import React from 'react';
import PropTypes from 'prop-types';
import { map } from 'lodash';
import { observer, PropTypes as MobxPropTypes } from 'mobx-react';
import { action, observable, computed } from 'mobx';
import createHistory from 'history/createHashHistory';
import ShowModel from '../../models/show';
import NoShowsFoundMessage from './none-found-message';
import Information from './information';
import Purchase from './purchase';
import Receipt from './receipt';
import Show from './show';
import './listing.scss';

@observer
export default class Listing extends React.Component {

    static propTypes = {
        shows: MobxPropTypes.observableArrayOf(
            PropTypes.instanceOf(ShowModel),
        ).isRequired,
    }
    @observable history;
    @observable displaying = {}
    @observable unlistenHistory;
    @observable lastSale;


    componentWillMount() {
        this.history = createHistory();
        this.onViewChange(this.history.location);
        this.historyUnlisten = this.history.listen(this.onViewChange);
    }

    @action.bound onViewChange(location) {
        const [_, view, identifier] = location.pathname.split('/');
        this.displaying = { view, identifier };
    }

    componentWillUnmount() {
        this.unlistenHistory();
    }

    @action.bound
    onDisplayInfo(show) {
        this.history.push(`/info/${show.identifier}`);
    }

    @action.bound
    onPurchase(show) {
        this.history.push(`/purchase/${show.identifier}`);
    }

    @action.bound
    onHideDisplay() {
        this.history.push('/');
    }

    @action.bound
    onPurchaseComplete(sale) {
        this.history.push(`/receipt/${sale.identifier}`);
        this.lastSale = sale;
    }

    @computed get Layer() {
        const { view } = this.displaying;
        if ('info' === view) {
            return Information;
        } else if ('purchase' === view) {
            return Purchase;
        } else if ('receipt' === view) {
            return Receipt;
        }
        return null;
    }

    @computed get actionsLayer() {
        const { Layer } = this;
        if (!Layer) { return null; }

        return (
            <Layer
                {...this.displaying}
                shows={this.props.shows}
                lastSale={this.lastSale}
                onPurchase={this.onPurchase}
                onPurchaseComplete={this.onPurchaseComplete}
                onCancel={this.onHideDisplay}
            />
        );
    }

    render() {
        const { shows } = this.props;

        return (
            <div className="hippo shows-listing">
                {this.actionsLayer}
                {map(shows, show => (
                    <Show
                        key={show.identifier}
                        show={show}
                        onPurchase={this.onPurchase}
                        displayShow={this.onDisplayInfo}
                    />
                ))}
                <NoShowsFoundMessage shows={shows} />
                <p className="credits">
                    listing generated by <a href="https://showmaker.com" target="_blank">ShowMaker.com</a>
                </p>
            </div>
        );
    }

}
