production:
  adapter: postgresql
  database: sm-dev
  host: /tmp
  pool:  5

development:
  adapter: postgresql
  database: sm-dev
  host: /tmp
  pool:  10

test:
  adapter: postgresql
  database: sm-dev
  host: /tmp
  pool:  5
